### ISSUE TITLE
PowertBI Rate Optimization - Reservation Recommendations Report not showing any data

### ISSUE THREAD

**Issue by echoesian** [microsoft/finops-toolkit#1004]
## 🐛 Problem
On the PowerBI Rate Optimization report, the Reservation Recommendations tab is showing blank data. The rest of the tab are fine.

## 🤔 Expected
Should have some data to show the recommendations as depicted on the documentation

![ReservationRecommendations](https://github.com/user-attachments/assets/c3646340-2ef4-461d-b0ef-c12f56f4f860)

**Comment by flanakin** [comment]
@echoesian My apologies for this. Our docs aren't very clear about how to set this up. We've seen a few cases of this. In order to see reservation recommendations, you will need to setup Cost Management exports for reservation recommendations and then configure the `Export Storage URL` to point to the location you setup the export for.

We'll keep this open to track 3 things:
1. Confirming this is the issue you're running into.
2. Adding support for all Cost Management dataset types in hubs to avoid the separate export URL.
3. Updating our documentation to be clearer about this requirement.

2 is in PR now. I'll add 3 to that now. Let us know about 1 when you get a chance.
