### ISSUE TITLE
[Power BI] Cost Summary Report v0.6 - Cannot schedule data refresh in Power BI Online

### ISSUE THREAD

**Issue by MS-mikeo** [microsoft/finops-toolkit#1033]
## 🐛 Problem
Deployed FinOps Hub v0.6 and when publishing the Cost Summary Power BI report to Power BI Online, I cannot schedule the data refresh.  It says "You can't schedule refresh for this semantic model because the following data sources currently don't support refresh:
Data source for Query1."

## 👣 Repro steps
1. Deploy FinOps Hub v0.6
2. Download Cost Summary Power BI report v0.6
3. Connect data and publish to Power BI Online.
4. Go to the Semantic Model and Schedule Refresh

## 🤔 Expected
Data source to be available to update credentials and then schedule refresh on recurring schedule.

## 📷 Screenshots
![image](https://github.com/user-attachments/assets/e2b948c2-ab85-4529-a1cb-13d07cb54741)

![image](https://github.com/user-attachments/assets/3400cc9e-35e6-4339-8262-e3c9b8e05b7e)

## 🙋‍♀️ Ask for the community
We could use your help:
1. Please vote this issue up (👍) to prioritize it.

**Comment by lundejd** [comment]
I'm actually having this issue when I moved from .4 to .5 and its a deal breaker.

**Comment by MS-mikeo** [comment]
@lundejd - If you add the same ingestion URL to both Hub Storage URL and Export Storage URL & then publish it should work for you.  You may need to delete the published PowerBI report/semantic model that had the issue in PowerBI Online first.

![image](https://github.com/user-attachments/assets/9696814f-2d1a-4c44-881f-75212b1e0faf)

This should be resolved in 0.7 because it will go back to one URL field.

**Comment by flanakin** [comment]
Thanks for reporting! Yes, please use the same URL for both parameters if you only need one. We have an open PR to update the docs. We'll consolidate both into a single parameter in a future release.

For some background, we investigated this and learned that Power BI isn't able to identify when connectors aren't used, so it perceives the empty URL as a problem even tho it's not used. We missed this when we rolled out 0.5 because all of our testing was done with both hubs and exports since we needed reservation recommendations, which weren't supported by hubs yet. (Note everything is now supported in 0.6.)
