### ISSUE TITLE
[Power BI] CostSummary.Storage report issue Cost Details - "We cannot apply operator >= to types List and Number"

### ISSUE THREAD

**Issue by josesarsa** [microsoft/finops-toolkit#1180]
## 🐛 Problem
I am receiving the following error with the report Costsummary. Finops hub 0.7. 1.0r2 scheme is used 

## 📷 Screenshots
![Image](https://github.com/user-attachments/assets/78a89ee7-6258-4659-a0a5-2ee8194d25a5)

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by josesarsa** [comment]
I am receiving the following error with the report Costsummary. Finops hub 0.7


![Image](https://github.com/user-attachments/assets/78a89ee7-6258-4659-a0a5-2ee8194d25a5)

**Comment by flanakin** [comment]
@josesarsa We talked to someone who ran into this and they refreshed the report and it was no longer happening. If you refresh, does the issue go away?

We haven't been able to reproduce the issue so far. Inspecting the queries for `>=` usage but didn't see where this could be happening. I suspect it may be something internal to one of the functions we use.

If you're still seeing this after refreshing, can you select the **RawData** step on the right and see if it has the same error? If not, go down the list of steps to find which one is failing.

**Comment by flanakin** [comment]
@josesarsa Sorry for the inconvenience here. We think the issue here is in how RegionStart/RegionEnd are being handled. Can you try removing those values and see if that resolves the issue for you? If you need to constrain the data, you can use **Number of Months**.

If you need to use a specific month, you can change the report local to be "en-US" until the next release comes out. We should have a fix ready soon. 

If you're comfortable with editing the queries, I can also tell you which lines need to be updated.

**Comment by josesarsa** [comment]
Yes, it is working if you remove the RangeStart/RangeEnd

**Comment by flanakin** [comment]
For anyone else who runs into this. We updated how dates are parsed in 0.8. Please update to FinOps toolkit 0.8 and create a new issue if you receive this (or any other) error.
