### ISSUE TITLE
Optimization Engine - Export-AADObjectsToBlobStorage runbook keeps failing

### ISSUE THREAD

**Issue by kevinrosal** [microsoft/finops-toolkit#1195]
## 🐛 Problem
Deployed AOE last month and we noticed that that runbook Export-AADObjectsToBlobStorage has been consistently failing or suspended after the deployment.
![Image](https://github.com/user-attachments/assets/ea8ad368-98b0-4dc6-9052-0c4ecfe5a079)

Message when suspended:
![Image](https://github.com/user-attachments/assets/e6c028ec-4a2b-498a-a182-c3a748e07aed)

Message when failed:
![Image](https://github.com/user-attachments/assets/36d19037-95fa-4e05-8c45-60fffea2d414)

## 👣 Repro steps
1. Go to AOE Automation Account
2. Click on runbooks
3. Export-AADObjectsToBlobStorage
4. See failed/suspended jobs

## 🤔 Expected
Runbook to run successfully without any issues

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by helderpinto** [comment]
Hi, @kevinrosal. Thanks for reporting this issue. The problem you described is well-known and documented [here](https://microsoft.github.io/finops-toolkit/optimization-engine/troubleshooting), in the _**Why is the Identity and Roles workbook empty and presenting error messages?**_ question. This is happening probably because your Entra ID tenant has too many objects.

For a Hybrid Worker work-around, see instructions [here](https://aka.ms/AzureOptimizationEngine/customize#-scale-aoe-runbooks-with-hybrid-worker). You can also filter the Entra ID users and groups, by creating the `AzureOptimization_AADObjectsUserFilter` and `AzureOptimization_AADObjectsGroupFilter` automation variables with an [Microsoft Graph OData filter](https://learn.microsoft.com/graph/filter-query-parameter?tabs=http).

**Comment by kevinrosal** [comment]
@helderpinto i see, ill try making a dedicated hybrid worker VM for our AOE automation account and see if this resolves the issue.

**Comment by helderpinto** [comment]
Thank you! If you don't mind, I'll archive this issue, @kevinrosal. Please, reopen the issue if the problem persists after trying the hybrid worker path.

**Comment by kevinrosal** [comment]
@helderpinto i've configured the hybrid worker now and followed the steps in the document you have referenced.

whenever i run the runbook i get the following error now:
![Image](https://github.com/user-attachments/assets/a7d76bc7-ae4a-4565-8588-437f3401a18e)

i verified that the automation account has Microsoft.Graph.Authentication module as well as the hybrid worker VM.

**Comment by helderpinto** [comment]
@kevinrosal, did you install the Microsoft Graph PowerShell SDK as administrator? The Hybrid Worker runs as LOCAL SYSTEM and the modules must be installed in the system-wide PowerShell folder.

**Comment by kevinrosal** [comment]
@helderpinto yup that was it, things are working now! appreciate the help
