### ISSUE TITLE
msexports_ETL_ingestion pipeline failed.

### ISSUE THREAD

**Issue by mark-gronow** [microsoft/finops-toolkit#664]
## 🐛 Problem
Hi, we are trying to use the FinOps Hub & its PowerBI reporting as a POC.  As we don't have access to EA or MCA costings, we are using the [sample FOCUS export report](https://microsoft.github.io/finops-toolkit/data#%EF%B8%8F-sample-exports) and have uploaded this file to the storage account created from the ARM deployment template - v0.3

The **msexports_ExecuteETL** pipeline runs successfully, however the **msexports_ETL_ingestion** pipeline fails with the error in the screenshot below.

Is this a bug or there an issue with the sample FOCUS costing export?

## 🤔 Expected
**msexports_ETL_ingestion** pipeline is status is succeeded

## 📷 Screenshots
![image](https://github.com/microsoft/finops-toolkit/assets/72824820/099adc69-7f9d-4fa4-b91f-e5bdae460e64)

## 🙋‍♀️ Ask for the community
We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by flanakin** [comment]
@mark-gronow Can you share the folder path you have in the `msexports` container?

**Comment by flanakin** [comment]
@mark-gronow I would recommend downloading the PBIX and using that file as is for your POC. The Power BI reports will not work with raw CSV files and you won't be able to mimic an export easily with the CSV files.

We've made some significant changes since you tried this so I'm going to close this as it won't work this way. If there's a specific POC feature you would like us to support, please create an issue with the details and we'll see what we can do.
