### ISSUE TITLE
Update FOCUS export to use new columns and updated column definitions on V1.0 cr release

### ISSUE THREAD

**Issue by thecloudman** [microsoft/finops-toolkit#711]
## ⚠️ Problem
A number of columns have changed in the spec from what was used to setup the first FOCUS export from azure. We need the export to be updated to support the changed columns

**Comment by flanakin** [comment]
This effort is in progress. For transparency, I'm creating a spec that covers 4 sets of changes:
- FOCUS 1.0 schema changes (new `1.0(v1)` dataset version)
- Feedback we've heard about the data from those using 1.0-preview
- New FOCUS-aligned version of the price sheet
- Internal optimizations to improve performance and scale

Not all of these will ship at the same time. None of these are committed yet and I don't have an ETA but I suspect the initial release will be focused on the 1.0 schema changes with some of the simpler feedback being addressed.

Here's a list of the feedback I'm tracking for the second bucket. If you would like to see something that isn't covered in this list, please let me know.

1. SkuId and SkuPriceId should have a clearer mapping to the price sheet.
2. Cost and price columns (e.g., ListUnitPrice, ContractedUnitPrice, *CostInUsd) should not be “0” when data is not available. Null (empty) should be used whenever data is not available.
3. Savings cannot be calculated accurately because cost and price columns (e.g., ListCost, ListUnitPrice) are sometimes null/0.
4. x_SkuMeterCategory, x_SkuMeterSubcategory, x_SkuDescription (ProductName), x_PricingUnitDescription (UnitOfMeasure), Region (ResourceLocation), and ConsumedService should be set correctly for EA Marketplace charges (see MCA data).
6. Add x_SkuOffer (OfferName) and x_SkuPlan (PlanName).
7. ServiceFamily for EA should not be hard-coded to “Compute”.
8. ChargeDescription should not be null.
9. x_SkuTier should be set to the tier when available.
10. Need an easy way to identify when ListCost/ContractedCost are double-counted for commitment/credit purchases.
11. Purchases that are manageable via API should have a ResourceId similar to deployed resources.

**Comment by flanakin** [comment]
Since this issue is explicitly referring to exports, I'll use this to track and share status on FOCUS 1.0 support in Cost Management, which is outside the toolkit; however, I'll also use this to track and share awareness of support for 1.0 in FinOps toolkit reports. We will do this as a transform in Power BI until Cost Management offers native support for 1.0.

**Comment by flanakin** [comment]
With all the hustle and bustle for FinOps X, I forgot to update this, but Cost Management shipped FOCUS 1.0 support in mid-June. FinOps toolkit 0.4 also now has FOCUS 1.0 support across hubs and all Power BI reports.
