### ISSUE TITLE
x_OnDemandCost is not equal to Effective cost for On-Demand Usage

### ISSUE THREAD

**Issue by DirkBrinkmann** [microsoft/finops-toolkit#728]
## 🐛 Problem
TODO: Based on a customer FOCUS export from End of May for the full month of April 2024 I can confirm, that x_OnDemandCost is not equal to Effective cost for rows with PricingCategory == "On-Demand"

## 👣 Repro steps
N/A

## 🤔 Expected
TODO: Sum of x_OnDemandCost should be equal to Effective cost for On-Demand Usage

## 📷 Screenshots
TODO: See real data in the screenshot.
![image](https://github.com/microsoft/finops-toolkit/assets/19854016/132b7b52-87c1-454f-bf4d-a884716c3ac7)

## ℹ️ Additional context
N/A

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by flanakin** [comment]
Discussed this with Dirk offline. This is a Cost Management issue that will be raised with support. We'll keep this open to track it.

**Comment by flanakin** [comment]
@DirkBrinkmann Any updates from support?

**Comment by flanakin** [comment]
There was a known issue with ContractedCost and PricingQuantity. I am not sure but am going to assume this was being impacted by that. We would need to check the x_PricingBlockSize to see if that was the issue. This seems like something different, but since this is a Cost Management issue and we don't have any data to validate, I'm going to close this here. There is nothing in the toolkit that would cause this.
