### ISSUE TITLE
[Cost Management] FOCUS 1.0 export includes extra BillingAccountType and SubAccountType columns

### ISSUE THREAD

**Issue by thecloudman** [microsoft/finops-toolkit#779]
## 🐛 Problem
**BillingAccountType**
The FOCUS 1.0 export has a column called BillingAccountType in it, this column is not part of the FOCUS 1.0 spec, if it is a provider column it must be x_BillingAccountType

**AvailabilityZone**
The FOCUS 1.0 spec contains AvailabilityZone in the spec, this column is not showing up in the FOCUS 1.0 export

**Provider**
The Column Provider in the FOCUS 1.0 spec is shown to have a Column ID of ProviderName and a Display Name of Provider, in the Focus 1.0 export data the column is generated as ProviderName, this need to be corrected to be Provider.

**BillingAccountID**
The data in BillingAccountID in the FOCUS 1.0 export is not formatted to meet the ID standard, it should be cleaned up to just show the billing ID and not the full path to the billing ID, currently it shows up as /providers/Microsoft.Billing/billingAccounts/[yourbillingaccountid], can this be corrected to just be [yourbillingaccountid]

**Comment by thecloudman** [comment]
@flanakin

**Comment by flanakin** [comment]
## BillingAccountType / SubAccountType
Yes, we're aware of the extra columns. This was my fault. I missed it when sharing the list of columns to be prefixed. I didn't change it in 1.0 because I didn't want to force people to change. Also, based on FOCUS conversations, it seems like this will come in. It's just a matter of when.

## AvailabilityZone
AvailabilityZone is optional in FOCUS 1.0.  I just re-read the spec and it seems this didn't make it in, but the intent was for the column to have a value when applicable, but if the provider cannot provide the value, then do not provide the column. The idea is that, if you see the column, then you know that you can expect to get results. Since we cannot provide results, we do not provide the column. If you would like to have AvailabilityZone specified, I would recommend sending this to the exports team directly (exportsready@ms) as it will require a lot of work and will need more explicit prioritization directly with the Cost Management team. In the meantime, I am tracking it as a gap.

## ProviderName
As you mentioned, the column ID is `ProviderName`. We're specifying this correctly. Fwiw, the plan is to change the display name to match the column ID because of the confusion this has caused.

## BillingAccountId
FOCUS does not specify the format for any IDs. We use the fully-qualified scope ID to make it easier to identify what kind of scope it is and to be able to uniquely identify it. For MCA, this would link to a billing profile and it's possible for 2 billing profiles in separate billing accounts to share the same ID, so this approach avoids that concern.

**Comment by flanakin** [comment]
For the BillingAccountId concern, I should add that we also offer x_BillingAccountId and x_BillingProfileId which give the number/guid only.

**Comment by flanakin** [comment]
I can keep this open to track BillingAccountType and SubAccountType, if you'd like. I know you're aware of the status of FOCUS, but happy to keep it open as a tracking item for anyone interested.

**Comment by thecloudman** [comment]
@flanakin You can close it. I just wanted to raise it for awareness so that updates are done to align.

**Comment by flanakin** [comment]
Out of curiosity, for anyone who lands here, I'd love to know whether you like having BillingAccountType and SubAccountType fields or not. We added it based on feedback early on, but it'd be great to know how people view them in the wild. If they don't provide enough value, we can remove them.

Vote 👍 to keep them or 👎 to remove them in the next FOCUS release.

**Comment by flanakin** [comment]
Actually, I'll add a poll to track this instead, so it's not lost in the issue list: https://github.com/microsoft/finops-toolkit/discussions/782
