### ISSUE TITLE
PowerBI Template App for MCA

### ISSUE THREAD

**Issue by steph409** [microsoft/finops-toolkit#865]
## 📝 Scenario

the template app in PowerBI looks like a really useful feature. It seems only to work for EA agreements: https://microsoft.github.io/finops-toolkit/power-bi/template-app

Is there a timeline when this will be available for MCA as well?

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by flanakin** [comment]
That Power BI report is a copy of the Cost Management template app for EA accounts. It uses data that is only available for EA and there is no direct parity with MCA. 

Please use the [Cost Management connector report](https://microsoft.github.io/finops-toolkit/power-bi/connector), which does work for MCA. The connector report is the subset of the EA template app that works for both plus some updates that we added since then.

As an FYI, the Cost Management connector is no longer being maintained. The Cost Management team is moving to exports as the medium to build Power BI reports. We'll have a version of this in 0.5. This will be the recommended approach as the connector does not support savings plan reporting and has a lower threshold of cost that can be monitored due to Power BI data size ingestion limitations. For details, see [Help me choose](https://microsoft.github.io/finops-toolkit/power-bi#%EF%B8%8F-help-me-choose).
